eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

server:
  port: 8083

springdoc:
  api-docs:
    path: /comment-service/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  application:
    name: comment-service
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      database: comment_service
      uri: mongodb://mongodb:27017/comment_service
    redis:
      url: redis://redis:6379
      port: 6379
  cache:
    type: redis
