server:
  port: 8084

STRIPE:
  API:
    KEY: ${STRIPE.API.KEY}
  WEBHOOK:
    SECRET: ${STRIPE.WEBHOOK.SECRET}

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      database: payment_service
      uri: mongodb://mongodb:27017/payment_service