eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

server:
  port: 8000

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/user_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://mysql:3306/user_service
    locations: classpath:db/migration
