eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/user_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://mysql:3306/user_service
    schemas: user_service
    locations: classpath:db/migration