eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

resilience4j:
  circuitbreaker:
    instances:
      order:
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      order:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/order_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://mysql:3306/order_service
    schemas: order_service
    locations: classpath:db/migration
  data:
    redis:
      url: redis://redis:6379
      port: 6379
  cache:
    type: redis
