eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

server:
  port: 8080

spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      database: product_service
      uri: mongodb://mongodb:27017/product_service
    redis:
      port: 6379
      url: redis://redis:6379
  cache:
    type: redis
