eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8888/eureka

server:
  port: 8081

springdoc:
  api-docs:
    path: /cart-service/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  application:
    name: cart-service
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:mysql://mysql:3306/cart_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://mysql:3306/cart_service
    locations: classpath:db/migration
  data:
    redis:
      url: redis://redis:6379
      port: 6379
  cache:
    type: redis